default:
	cd generate_camera_trajectory_random_walk && make
	cd generate_hdf5_from_exr && make
	cd generate_octomap && make
	cd generate_octomap_samples && make
	cd generate_oriented_bounding_box && make
	cd generate_ray_intersections && make
